### ISSUE TITLE
ВЛ60ПК Alt+N выключает соответствующий МВN

### ISSUE THREAD

**Issue by karbazol** [maisvendoo/TrueRailway#29]
Включить электровоз ВЛ60ПК:
 - Shift+U
 - Shift+O
 - Shift+P
 - K
 - Shift+T
 - Shift+E
 - Shift+5
 - Shift+6
 - Shift+7
 - Shift+R
 - Shift+F
 - Shift+Y
Красные лампы гаснут
Нажать последовательно:
 - Alt+5
 - Alt+6
 - Alt+7
Ожидаемо: Кран №395 переключается последовательно в положения Va, V, VI
Неожидано: выключаются мотор-вентиляторы, зажигаются соответствующие красные лампы

**Comment by karbazol** [comment]
Забыл упомянуть, что всё происходит на Windows 10

**Comment by maisvendoo** [comment]
Исправлено в текущей актуальной версии, а скорее всего еще в версии 1.3.0. Закрываю
