### ISSUE TITLE
ВЛ60ПК не снижается давление в напорной магистрали

### ISSUE THREAD

**Issue by karbazol** [maisvendoo/TrueRailway#30]
Добрый день!
Это так и должно быть?
Пытаюсь стравить воздух из напорной магистрали: включаю экстренное торможение на стоянке, дожидаюсь полного наполнения тормозных цилиндров. Отпускаю тормоза.
Ожидаю, что давление в напорной магистрали снизится. Давление не снижается.

**Comment by maisvendoo** [comment]
Теперь напорная магистраль моделируется нормально. Закрыто
