### ISSUE TITLE
Поддержка qt5

### ISSUE THREAD

**Issue by SergeyDjam** [maisvendoo/TrueRailway#49]
Очень и очень многие системы на qt5, и лишь самые смелые и переходят но не всегда и не везде на qt6.

Поэтому наверное имеет смысл вернуть поддержку qt5 тем более что он еще хотя бы по старой двойной лицензии... В то время как qt6 имеет крайне странную лицензию и есть не малые риски потери доступа к нему. 

Пусть бы минимальная версия qt5 ,была бы 5.15, это удобно и поддерживается до сих пор

**Comment by maisvendoo** [comment]
Не будем переходить. Много накладных расходов, извините. Тем более впереди Qt7 - и так засиделись. Причина есть техническая - то что вырезали в Qt6 заменили появившимися там функциями, а Qt5 этого нет

**Comment by maisvendoo** [comment]
Это закрываю. Не будем заниматься точно
